Controllers/empController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using IoTHUB_v1._0.library;
using IoTHUB_v1._0.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace IoTHUB_v1._0.Controllers
{

    public class EmpController : Controller
    {
        private readonly ILogger<EmpController> _logger;
        private SerialPortConnector _serialPortConnector;

        public EmpController(ILogger<EmpController> logger)
        {
            _logger = logger;
            _serialPortConnector = new SerialPortConnector();
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Send(string command, string roomNumber)
        {
            try
            {
                _serialPortConnector.Send(command + roomNumber);
                return Ok("sent");
            }
            catch (Exception)
            {
                return BadRequest("failed");
            }
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Views/Emp/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" asp-area="" asp-controller="Emp" asp-action="Index">DeviceControl</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Viewemp">Profile</a>
                </li>
            </ul>
            <span class="navbar-text">
                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>

            </span>
        </div>
    </nav>
</header>

<h2 class="text-center m-3">IoTHUB - Control your devices from anywhere<span id="time" class="m-3"></span></h2>
<hr />
<div class="row">
    <div class="col-6 offset-3">
        <div class="card">
            <div class="card-header bg-primary text-white">Fan</div>
            <div class="card-body">
                <div class="m-3">
                    <span class="badge badge-success" style="font-size:15px;">Clockwise:</span>
                    <input class="switch" data-room="1" type="checkbox" data-toggle="toggle" data-onstyle="primary" />
                    <span class="float-right off" data-room="1"></span>
                </div>
                <hr />
                <div class="m-3">
                    <span class="badge badge-success" style="font-size:15px;">Anticlockwise:</span>
                    <input class="switch" data-room="2" type="checkbox" data-toggle="toggle" data-onstyle="primary" />
                    <span class="float-right off" data-room="2"></span>
                </div>
                <hr />
                <div class="m-3">
                    <span class="badge badge-success" style="font-size:15px;">LED 1:</span>
                    <input class="switch" data-room="3" type="checkbox" data-toggle="toggle" data-onstyle="primary" />
                    <span class="float-right off" data-room="3"></span>
                </div>
                <hr />
                <div class="m-3">
                    <span class="badge badge-success" style="font-size:15px;">Blynk LED :</span>
                    <input class="switch" data-room="4" type="checkbox" data-toggle="toggle" data-onstyle="primary" />
                    <span class="float-right off" data-room="4"></span>
                </div>
                <hr />

            </div>

        </div>
    </div>
</div>


@section Scripts{
    <script>
        $(() => {
            toastr.options = {
                "preventDuplicates": true
            }

            $switch = $(".switch")

            $switch.on('change', async (e) => {
                var target = e.target
                var roomNo = $(target).data('room')

                var switchElement = $(`.switch[data-room='${roomNo}']`)
                var bulbElement = $(`.float-right[data-room='${roomNo}']`)

                var switchValue = $(target).prop('checked')
                var command = switchValue == true ? 'on' : 'off'

                $.ajax({
                    url: `/emp/send?command=${command}&&roomNumber=${roomNo}`,
                    method: 'Get',
                    success: (result) => {
                        if (switchValue)
                            $(bulbElement).removeClass("off").addClass("on")
                        else
                            $(bulbElement).removeClass("on").addClass("off")

                        toastr.success('Command completed successfully!')
                    },
                    error: (error) => {
                        $(switchElement).bootstrapToggle('off', true)
                        $(bulbElement).removeClass("on").addClass("off")

                        toastr.error('Could not complete command. Please try again!')
                    }
                })

            })

            setInterval(function () {
                var date = new Date().toLocaleString()
                $("#time").html(date)
            }, 1000)
        })
    </script>
}